name: proprint
description: "An Ecommerce Store"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1
  mime: ^2.0.0
  path: ^1.9.0
  uuid: ^4.5.1
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.20.2
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/pro_print_app_icon.png'
  adaptive_icon_foreground: 'assets/images/pro_print_app_icon_foreground.png'
  adaptive_icon_background: '#444444'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Hacen Tunisia.ttf
